// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package protoDoc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Text                 []byte   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Time                 string   `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Message) GetText() []byte {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *Message) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type Identity struct {
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (m *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(m, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Subscription struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Id                   *Identity  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *Subscription) GetId() *Identity {
	if m != nil {
		return m.Id
	}
	return nil
}

type Subs_Request struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subs_Request) Reset()         { *m = Subs_Request{} }
func (m *Subs_Request) String() string { return proto.CompactTextString(m) }
func (*Subs_Request) ProtoMessage()    {}
func (*Subs_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *Subs_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subs_Request.Unmarshal(m, b)
}
func (m *Subs_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subs_Request.Marshal(b, m, deterministic)
}
func (m *Subs_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subs_Request.Merge(m, src)
}
func (m *Subs_Request) XXX_Size() int {
	return xxx_messageInfo_Subs_Request.Size(m)
}
func (m *Subs_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Subs_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Subs_Request proto.InternalMessageInfo

func (m *Subs_Request) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Subs_Request) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Bool struct {
	Flag                 bool     `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (m *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(m, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

type Tag struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type Tags struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tags) Reset()         { *m = Tags{} }
func (m *Tags) String() string { return proto.CompactTextString(m) }
func (*Tags) ProtoMessage()    {}
func (*Tags) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *Tags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tags.Unmarshal(m, b)
}
func (m *Tags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tags.Marshal(b, m, deterministic)
}
func (m *Tags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tags.Merge(m, src)
}
func (m *Tags) XXX_Size() int {
	return xxx_messageInfo_Tags.Size(m)
}
func (m *Tags) XXX_DiscardUnknown() {
	xxx_messageInfo_Tags.DiscardUnknown(m)
}

var xxx_messageInfo_Tags proto.InternalMessageInfo

func (m *Tags) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "project.Message")
	proto.RegisterType((*Identity)(nil), "project.Identity")
	proto.RegisterType((*Subscription)(nil), "project.Subscription")
	proto.RegisterType((*Subs_Request)(nil), "project.Subs_Request")
	proto.RegisterType((*Bool)(nil), "project.Bool")
	proto.RegisterType((*Tag)(nil), "project.Tag")
	proto.RegisterType((*Tags)(nil), "project.Tags")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x31, 0x4f, 0x84, 0x40,
	0x10, 0x85, 0x05, 0x4e, 0x81, 0xb9, 0x8b, 0x39, 0xb7, 0x91, 0x50, 0x21, 0x15, 0x85, 0x21, 0x17,
	0xac, 0x6d, 0xb4, 0xb2, 0x30, 0x31, 0xeb, 0xf5, 0x97, 0xe5, 0x58, 0xd7, 0x35, 0x70, 0x8b, 0xec,
	0x90, 0xe8, 0xbf, 0x37, 0x0c, 0x48, 0x21, 0x76, 0x6f, 0x37, 0x6f, 0xe6, 0xbd, 0x2f, 0x03, 0x61,
	0x63, 0x55, 0xde, 0x76, 0x06, 0x0d, 0xf3, 0xdb, 0xce, 0x7c, 0xc8, 0x23, 0xa6, 0x8f, 0xe0, 0x3f,
	0x4b, 0x6b, 0x85, 0x92, 0x6c, 0x0b, 0x1e, 0x0a, 0x15, 0x39, 0x89, 0x93, 0x85, 0x7c, 0x90, 0x8c,
	0xc1, 0x0a, 0xe5, 0x17, 0x46, 0x6e, 0xe2, 0x64, 0x1b, 0x4e, 0x9a, 0xfe, 0x74, 0x23, 0x23, 0x8f,
	0x6c, 0xa4, 0xd3, 0x18, 0x82, 0xa7, 0x4a, 0x9e, 0x50, 0xe3, 0x37, 0xbb, 0x04, 0x57, 0x57, 0x34,
	0x71, 0xce, 0x5d, 0x5d, 0xa5, 0x07, 0xd8, 0xbc, 0xf6, 0xa5, 0x3d, 0x76, 0xba, 0x45, 0x6d, 0x4e,
	0xec, 0x16, 0x82, 0x66, 0x0c, 0xb4, 0x91, 0x93, 0x78, 0xd9, 0xba, 0xd8, 0xe6, 0x53, 0x99, 0x7c,
	0x6a, 0xc2, 0x67, 0x07, 0xbb, 0x99, 0xb7, 0xad, 0x8b, 0xab, 0xd9, 0xf7, 0x1b, 0x46, 0x01, 0xbb,
	0x31, 0xe0, 0xc0, 0xe5, 0x67, 0x2f, 0x2d, 0xfe, 0x83, 0xf1, 0xb7, 0x52, 0x0c, 0xab, 0x07, 0x63,
	0xea, 0x01, 0xe5, 0xad, 0x9e, 0xac, 0x01, 0x27, 0x9d, 0x5e, 0x83, 0xb7, 0x17, 0x6a, 0xb9, 0x64,
	0x18, 0xda, 0x0b, 0x65, 0x89, 0x5f, 0xa8, 0xb1, 0xfb, 0xc0, 0x2f, 0x94, 0x2d, 0xee, 0x21, 0x7c,
	0xe9, 0xcb, 0x5a, 0xdb, 0x77, 0xd9, 0xb1, 0x1d, 0xf8, 0xd3, 0x83, 0x2d, 0xc8, 0xe2, 0x25, 0x43,
	0x7a, 0x56, 0x5e, 0xd0, 0x4d, 0xee, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x76, 0x3a, 0x55, 0xf5,
	0xa0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PublisherClient is the client API for Publisher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PublisherClient interface {
	Publish(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Identity, error)
}

type publisherClient struct {
	cc *grpc.ClientConn
}

func NewPublisherClient(cc *grpc.ClientConn) PublisherClient {
	return &publisherClient{cc}
}

func (c *publisherClient) Publish(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Identity, error) {
	out := new(Identity)
	err := c.cc.Invoke(ctx, "/project.Publisher/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublisherServer is the server API for Publisher service.
type PublisherServer interface {
	Publish(context.Context, *Message) (*Identity, error)
}

// UnimplementedPublisherServer can be embedded to have forward compatible implementations.
type UnimplementedPublisherServer struct {
}

func (*UnimplementedPublisherServer) Publish(ctx context.Context, req *Message) (*Identity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}

func RegisterPublisherServer(s *grpc.Server, srv PublisherServer) {
	s.RegisterService(&_Publisher_serviceDesc, srv)
}

func _Publisher_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.Publisher/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).Publish(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _Publisher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "project.Publisher",
	HandlerType: (*PublisherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _Publisher_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg.proto",
}
